[package]
name = "serde"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
nom = "7.1.3"
bitflags = "2.6.0"

#base-x = "0.2.0"
data-encoding = "2.6.0"

rand = "0.9.0-alpha.2"
itertools = "0.13.0"
